---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: foo-dev-review-frontend
  namespace: argocd
spec:
  generators:
  - pullRequest:
      requeueAfterSeconds: 30
      github:
        owner: Gustavmk
        repo: kind-cluster # This is the application source code repo
        tokenRef:
          secretName: github-token
          key: token
  template:
    metadata:
      name: 'review-vote-app-branch-{{branch}}-pr-{{number}}'
    spec:
      source:
        repoURL: 'https://github.com/gustavmk/kind-cluster.git'
        targetRevision: '{{head_sha}}'
        path: apps/tests/vote-app
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: 'review-vote-app-branch-{{branch}}-pr-{{number}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true