---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: foo-dev-review-frontend
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: Gustavmk
        repo: kind-cluster # This is the application source code repo
        tokenRef:
          secretName: github-token
          key: token
        labels:
        - deploy # label on PR that trigger review app
  template:
    metadata:
      name: 'voting-app-dev-frontend-{{branch}}-{{number}}'
    spec:
      source:
        repoURL: git@github.com:gustavmk/kind-cluster.git
        targetRevision: main
        path: apps/dev/frontend
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: foo-dev
